const MAX_FIELD_BYTE_SIZE = 31
const PHOTO_PACK_SIZE = 32
const DELIMITER_ARRAY_SIZE = 18
const DATA_ARRAY_SIZE = 1536

export const DELIMITER_POSITION = {
  REFERENCE_ID: 2,
  NAME: 3,
  DOB: 4,
  GENDER: 5,
  PINCODE: 11,
  STATE: 13,
  PHOTO: 18,
}

export {
  MAX_FIELD_BYTE_SIZE,
  PHOTO_PACK_SIZE,
  DELIMITER_ARRAY_SIZE,
  DATA_ARRAY_SIZE,
}

export const DEMO_PRIVATEKEY = "EKFZg3P2XGXXsDVSuZX55tww9mpB8a7nwEZ9KYdzpwK3hJNDTshR"