const REFERENCE_ID_POSITION = 2;
const NAME_POSITION = 3;
const DOB_POSITION = 4;
const GENDER_POSITION = 5;
const PINCODE_POSITION = 11;
const STATE_POSITION = 13;
const PHOTO_POSITION = 18;
const MAX_FIELD_BYTE_SIZE = 31;
const PHOTO_PACK_SIZE = 32;

export {
  REFERENCE_ID_POSITION,
  NAME_POSITION,
  DOB_POSITION,
  GENDER_POSITION,
  PINCODE_POSITION,
  STATE_POSITION,
  PHOTO_POSITION,
  MAX_FIELD_BYTE_SIZE,
  PHOTO_PACK_SIZE,
};
